# Customized configuration file for goreleaser (initially taken from awsls repo)
builds:
  - 
    goos:
      - darwin
      - linux
      - windows
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.CommitDate}}

archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
